# Đổi cổng chạy server sang 8081 để tránh trùng lặp
server.port=8082

# ===============================
# CẤU HÌNH DATABASE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://ep-polished-mouse-aodqvugz-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KoVfX2IFY1iQ
spring.datasource.driver-class-name=org.postgresql.Driver

# Cho phép Spring Boot tự động tạo bảng (table) dựa trên code Java
spring.jpa.hibernate.ddl-auto=update
# Hiển thị câu lệnh SQL ra Terminal để dễ debug
spring.jpa.show-sql=true